#pragma once

#define LAYER_ID_GLOBAL -1

// Standard and Big ARTSEY layer IDs
#define LAYER_ID_BASE 0
#define LAYER_ID_NUMBERS 1
#define LAYER_ID_SYMBOLS 2
#define LAYER_ID_PARENTHETICALS 3
#define LAYER_ID_NAVIGATION 4
#define LAYER_ID_CUSTOM 5
#define LAYER_ID_MOUSE 6
#define LAYER_ID_BIG_SYM 7
#define LAYER_ID_BIG_FUN 8

// 40% ARTSEY layer IDs
#define LAYER_ID_40P_BASE 0
#define LAYER_ID_40P_FUNCTION 1
#define LAYER_ID_40P_NAVIGATION 2
#define LAYER_ID_40P_LEFT_BASE 3
#define LAYER_ID_40P_LEFT_NUMBERS 4
#define LAYER_ID_40P_LEFT_SYMBOLS 5
#define LAYER_ID_40P_LEFT_PARENTHETICALS 6
#define LAYER_ID_40P_LEFT_NAVIGATION 7
#define LAYER_ID_40P_LEFT_CUSTOM 8
#define LAYER_ID_40P_LEFT_MOUSE 9
#define LAYER_ID_40P_LEFT_BIG_SYM 10
#define LAYER_ID_40P_LEFT_BIG_FUN 11
#define LAYER_ID_40P_RIGHT_BASE 12
#define LAYER_ID_40P_RIGHT_NUMBERS 13
#define LAYER_ID_40P_RIGHT_SYMBOLS 14
#define LAYER_ID_40P_RIGHT_PARENTHETICALS 15
#define LAYER_ID_40P_RIGHT_NAVIGATION 16
#define LAYER_ID_40P_RIGHT_CUSTOM 17
#define LAYER_ID_40P_RIGHT_MOUSE 18
#define LAYER_ID_40P_RIGHT_BIG_SYM 19
#define LAYER_ID_40P_RIGHT_BIG_FUN 20
