#pragma once

#define LAYER_ID_GLOBAL -1
#define LAYER_ID_BASE 0
#define LAYER_ID_NUMBERS 1
#define LAYER_ID_SYMBOLS 2
#define LAYER_ID_PARENTHETICALS 3
#define LAYER_ID_NAVIGATION 4
#define LAYER_ID_CUSTOM 5
#define LAYER_ID_MOUSE 6
#define LAYER_ID_BIG_SYM 7
#define LAYER_ID_BIG_FUN 8
